version: "3"

services:
  facegeneration:
    build: .
    restart: always
    environment:
      - GPU_ID=${GPU_ID}
      - BFM_DIR=${BFM_DIR}
      - REC_CHECKPOINT_PATH=${REC_CHECKPOINT_PATH}
      - API_PORT=${API_PORT}
      - DLIB_MODEL_PATH=${DLIB_MODEL_PATH}
      - REC_CHECKPOINT_DIR=${REC_CHECKPOINT_DIR}
      - FILESERVER_URL=${FILESERVER_URL}
      - SECRET_KEY=${SECRET_KEY}
    runtime: nvidia
    ports:
      - "35558:35558"
    networks:
      - FaceGeneration

networks:
  FaceGeneration:
    external: true
