GPU_ID = "GPU_ID"
BFM_DIR = 'BFM_DIR'
REC_CHECKPOINT_PATH = 'REC_CHECKPOINT_PATH'
API_PORT = "API_PORT"
PORT = "PORT"
DLIB_MODEL_PATH = "DLIB_MODEL_PATH"
REC_CHECKPOINT_DIR = 'REC_CHECKPOINT_DIR'

BASE64_IMAGE = "base64_image"
NUMPY_IMAGE = "numpy_image" 

FILE_SERVER_URL = "FILE_SERVER_URL"
FILE_SERVER_GET_URL = "FILE_SERVER_GET_URL"
MAX_RETRIES = "MAX_RETRIES"
TIME_OUT = "TIME_OUT"

URL_IMAGE_PROXY = "urlImageProxy"
FILESERVER_URL = "FILESERVER_URL"
SECRET_KEY = "secret_key"

INPUT_LIST = "input_list"
ID = "id"
DESIRED_ANGLE = "desired_angle"
STEP = "step"
